[package]
name = "edgeware-runtime"
version = "0.1.0"
authors = ["Commonwealth Labs <hello@commonwealth.im>"]

[dependencies]
rustc-hex = "1.0"
hex-literal = "0.1.0"
serde = { version = "1.0", default-features = false }
serde_derive = { version = "1.0", optional = true }
safe-mix = { version = "1.0", default-features = false }
parity-codec = "2.0"
parity-codec-derive = "2.0"
sr-std = { git = "https://github.com/paritytech/substrate" }
sr-io = { git = "https://github.com/paritytech/substrate" }
srml-support = { git = "https://github.com/paritytech/substrate" }
substrate-primitives = { git = "https://github.com/paritytech/substrate" }
substrate-keyring = { git = "https://github.com/paritytech/substrate" }
srml-balances = { git = "https://github.com/paritytech/substrate" }
srml-consensus = { git = "https://github.com/paritytech/substrate" }
srml-aura = { git = "https://github.com/paritytech/substrate" }
srml-executive = { git = "https://github.com/paritytech/substrate" }
sr-primitives = { git = "https://github.com/paritytech/substrate" }
srml-contract = { git = "https://github.com/paritytech/substrate" }
srml-grandpa = { git = "https://github.com/paritytech/substrate" }
srml-session = { git = "https://github.com/paritytech/substrate" }
srml-system = { git = "https://github.com/paritytech/substrate" }
srml-timestamp = { git = "https://github.com/paritytech/substrate" }
srml-upgrade-key = { git = "https://github.com/paritytech/substrate" }
substrate-client = { git = "https://github.com/paritytech/substrate", optional = true }
sr-version = { git = "https://github.com/paritytech/substrate" }
node-primitives = { git = "https://github.com/paritytech/substrate" }
substrate-consensus-aura-primitives = { git = "https://github.com/paritytech/substrate" }
edge-delegation = { path = "../../modules/edge-delegation" }
edge-governance = { path = "../../modules/edge-governance" }
edge-identity = { path = "../../modules/edge-identity" }

[features]
default = ["std"]
std = [
	"parity-codec/std",
	"substrate-primitives/std",
	"substrate-client/std",
	"sr-std/std",
	"sr-io/std",
	"srml-support/std",
	"srml-balances/std",
	"srml-consensus/std",
	"srml-executive/std",
	"srml-aura/std",
	"sr-primitives/std",
	"srml-contract/std",
	"srml-grandpa/std",
	"srml-session/std",
	"srml-system/std",
	"srml-timestamp/std",
	"srml-upgrade-key/std",
	"sr-version/std",
	"node-primitives/std",
	"serde_derive",
	"serde/std",
	"safe-mix/std",
	"substrate-client",
	"substrate-consensus-aura-primitives/std",
	"edge-delegation/std",
	"edge-governance/std",
	"edge-identity/std",
]
