[package]
name = "edgeware-runtime"
version = "0.1.2"
authors = ["Commonwealth Labs <hello@commonwealth.im>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
integer-sqrt = { git = "https://github.com/paritytech/integer-sqrt-rs.git" }
safe-mix = { version = "1.0", default-features = false}
parity-codec-derive = { version = "^2.1" }
parity-codec = { version = "^2.1", default-features = false }
substrate-primitives = { git = "https://github.com/paritytech/substrate", branch = "v0.9", default-features = false }
substrate-client = { git = "https://github.com/paritytech/substrate", branch = "v0.9", default-features = false }
sr-std = { git = "https://github.com/paritytech/substrate", branch = "v0.9", default-features = false }
sr-io = { git = "https://github.com/paritytech/substrate", branch = "v0.9", default-features = false }
srml-support = { git = "https://github.com/paritytech/substrate", branch = "v0.9", default-features = false }
srml-balances = { git = "https://github.com/paritytech/substrate", branch = "v0.9", default-features = false }
srml-consensus = { git = "https://github.com/paritytech/substrate", branch = "v0.9", default-features = false }
srml-executive = { git = "https://github.com/paritytech/substrate", branch = "v0.9", default-features = false }
srml-aura = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "v0.9" }
sr-primitives = { git = "https://github.com/paritytech/substrate", branch = "v0.9", default-features = false }
srml-session = { git = "https://github.com/paritytech/substrate", branch = "v0.9", default-features = false }
srml-system = { git = "https://github.com/paritytech/substrate", branch = "v0.9", default-features = false }
srml-timestamp = { git = "https://github.com/paritytech/substrate", branch = "v0.9", default-features = false }
srml-upgrade-key = { git = "https://github.com/paritytech/substrate", branch = "v0.9", default-features = false }
sr-version = { git = "https://github.com/paritytech/substrate", branch = "v0.9", default-features = false }
substrate-consensus-aura-primitives = { git = "https://github.com/paritytech/substrate", branch = "v0.9", default-features = false }
edge-delegation = { path = "../../modules/edge-delegation", default-features = false }
edge-governance = { path = "../../modules/edge-governance", default-features = false }
edge-identity = { path = "../../modules/edge-identity", default-features = false }

[features]
default = []
std = [
	"safe-mix/std",
	"parity-codec/std",
	"substrate-primitives/std",
	"substrate-client/std",
	"sr-std/std",
	"sr-io/std",
	"srml-support/std",
	"srml-balances/std",
	"srml-consensus/std",
	"srml-executive/std",
	"srml-aura/std",
	"sr-primitives/std",
	"srml-session/std",
	"srml-system/std",
	"srml-timestamp/std",
	"srml-upgrade-key/std",
	"sr-version/std",
  "edge-delegation/std",
  "edge-governance/std",
  "edge-identity/std",
]

[profile.release]
panic = "abort"
lto = true

[workspace]
members = []
